language: csharp
mono: 4.2.1

sudo: false

cache:
  directories:
  - ~/.openra/Content

addons:
  apt:
    packages:
    - liblua5.1-0
    - p7zip-full

script:
 - cd OpenRA.Mods.RA2
 - xbuild
 - cd ../../..
 - mkdir -p ~/.openra/mods
 - mv OpenRA/ra2 ~/.openra/mods/ra2
 - git clone https://github.com/OpenRA/OpenRA.git
 - cd OpenRA
 - travis_retry make dependencies
 - make all
 - travis_retry ~/.openra/mods/ra2/fetch-content.sh
 - mono --debug OpenRA.Utility.exe ra2 --check-yaml
 - mono --debug OpenRA.Utility.exe ra2 --check-sequence-sprites

branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
