language: csharp
mono: 4.2.1

sudo: false

cache:
  directories:
  - ~/.openra/Content

addons:
  apt:
    packages:
    - liblua5.1-0
    - p7zip-full

script:
 - cd ../..
 - mkdir -p ~/.openra/mods
 - mv OpenRA/ra2 ~/.openra/mods/ra2
 - git clone https://github.com/OpenRA/OpenRA.git
 - cd OpenRA
 - travis_retry make dependencies
 - make all
 - ln -sf ~/build/OpenRA/OpenRA.Game.exe ~/.openra/mods/ra2/OpenRA.Mods.RA2/dependencies
 - ln -sf ~/build/OpenRA/mods/common/OpenRA.Mods.Common.dll ~/.openra/mods/ra2/OpenRA.Mods.RA2/dependencies
 - ln -sf ~/build/OpenRA/mods/ra/OpenRA.Mods.RA.dll ~/.openra/mods/ra2/OpenRA.Mods.RA2/dependencies
 - ln -sf ~/build/OpenRA/mods/ts/OpenRA.Mods.TS.dll ~/.openra/mods/ra2/OpenRA.Mods.RA2/dependencies
 - ln -sf ~/build/OpenRA/thirdparty/download/Eluant.dll ~/.openra/mods/ra2/OpenRA.Mods.RA2/dependencies
 - pushd ~/.openra/mods/ra2/OpenRA.Mods.RA2 && xbuild && popd
 - travis_retry ~/.openra/mods/ra2/fetch-content.sh
 - mono --debug OpenRA.Utility.exe ra2 --check-yaml
 - mono --debug OpenRA.Utility.exe ra2 --check-sequence-sprites

branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
